project_id = "mlbeciqslbemjrezgclq"

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-public-key]
verify_jwt = false

[functions.auto-complete-lessons]
verify_jwt = false

[functions.secure-login]
verify_jwt = false
